# Generated by Django 3.2.10 on 2021-12-23 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FilmLocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.SmallIntegerField()),
                ('location', models.CharField(max_length=500)),
                ('fun_fact', models.TextField()),
                ('actor', models.ManyToManyField(to='main.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.director')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.distributor')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.productioncompany')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.writer')),
            ],
        ),
    ]
