# Generated by Django 3.2.10 on 2021-12-23 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.SmallIntegerField()),
                ('actor', models.ManyToManyField(to='main.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.director')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.distributor')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.productioncompany')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.writer')),
            ],
        ),
        migrations.CreateModel(
            name='ShootingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=500)),
                ('fun_fact', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='FilmLocationData',
        ),
    ]
