# Generated by Django 3.2.10 on 2021-12-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211223_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_year']},
        ),
        migrations.AddField(
            model_name='shootinglocation',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shootinglocation',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
